// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PreprocessingData.Models;

public partial class ElectioneerStagingContext : DbContext
{
    public ElectioneerStagingContext(DbContextOptions<ElectioneerStagingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<OhioElections> OhioElections { get; set; }

    public virtual DbSet<OhioPartyLookup> OhioPartyLookup { get; set; }

    public virtual DbSet<OhioVoterElectionCount> OhioVoterElectionCount { get; set; }

    public virtual DbSet<OhioVoterElectionRecord> OhioVoterElectionRecord { get; set; }

    public virtual DbSet<OhioVoterLoad> OhioVoterLoad { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OhioElections>(entity =>
        {
            entity.HasKey(e => e.ElectionID).HasName("PK__OhioElec__C626C7C6A4048022");

            entity.ToTable("OhioElections", "staging");

            entity.Property(e => e.ElectionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ElectionType)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OhioPartyLookup>(entity =>
        {
            entity.HasKey(e => e.MainPartyId).HasName("PK__OhioPart__93A112BF8D94015B");

            entity.ToTable("OhioPartyLookup", "staging");

            entity.Property(e => e.MainPartyId).ValueGeneratedNever();
            entity.Property(e => e.OhioLookupCode)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.PartyName).HasMaxLength(128);
        });

        modelBuilder.Entity<OhioVoterElectionCount>(entity =>
        {
            entity.HasKey(e => e.ElectionCountID).HasName("PK__OhioVote__5CAB33D172C1CA31");

            entity.ToTable("OhioVoterElectionCount", "staging");

            entity.HasIndex(e => e.SOS_Voter_Id, "IX_OhioVoterElectionCount_SOS_Voter_ID");

            entity.Property(e => e.SOS_Voter_Id)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OhioVoterElectionRecord>(entity =>
        {
            entity.HasKey(e => e.ElectionRecordId).HasName("PK__OhioVote__387C6E89E7E3CF52");

            entity.ToTable("OhioVoterElectionRecord", "staging");

            entity.HasIndex(e => e.SOS_Voter_Id, "IX_OhioVoterElectionRecord_SOS_Voter_ID");

            entity.HasIndex(e => e.SOS_Voter_Id, "IX_OhioVoterElectionRecord_SOS_Voter_ID_Data");

            entity.Property(e => e.ElectionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SOS_Voter_Id)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.VoterRegisteredAs)
                .HasMaxLength(2)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OhioVoterLoad>(entity =>
        {
            entity.HasKey(e => e.StagingID).HasName("PK__OhioVote__8C047280B6F2CF2C");

            entity.ToTable("OhioVoterLoad", "staging");

            entity.Property(e => e.Career_Center)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.City_School_District)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Congressional_District)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.County_Court__District)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.County_Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.County_Number)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Court_of_Appeals)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Date_Of_Birth)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Education_Service_Center)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Exempted_Village_School_District)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.First_Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Last_Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Library_District)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Local_School_District)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_Address1)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_Address_2_)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_Country)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_Postal_Code)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_State)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_Zip)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Mailing_Zip_Plus_4)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Middle_Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Municipal_Court_District)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Party_Affiliation)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Precinct)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Precinct_Code_)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Registration_Date)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Residential_Address1)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Residential_Address_2_)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Residential_City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Residential_Country)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Residential_Postal_Code)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Residential_State)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Residential_Zip)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Residential_Zip_Plus_4)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.SOS_Voter_Id)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.State_Board_of_Education)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.State_Representative_District_)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.State_Senate_District)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Suffix)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Township)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Village)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Voter_Status)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Ward)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}