// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreprocessingData.Models;

public partial class OhioVoterLoad
{
    public long StagingID { get; set; }

    public string SOS_Voter_Id { get; set; }

    public string County_Number { get; set; }

    public string County_Id { get; set; }

    public string Last_Name { get; set; }

    public string First_Name { get; set; }

    public string Middle_Name { get; set; }

    public string Suffix { get; set; }

    public string Date_Of_Birth { get; set; }

    public string Registration_Date { get; set; }

    public string Voter_Status { get; set; }

    public string Party_Affiliation { get; set; }

    public string Residential_Address1 { get; set; }

    public string Residential_Address_2_ { get; set; }

    public string Residential_City { get; set; }

    public string Residential_State { get; set; }

    public string Residential_Zip { get; set; }

    public string Residential_Zip_Plus_4 { get; set; }

    public string Residential_Country { get; set; }

    public string Residential_Postal_Code { get; set; }

    public string Mailing_Address1 { get; set; }

    public string Mailing_Address_2_ { get; set; }

    public string Mailing_City { get; set; }

    public string Mailing_State { get; set; }

    public string Mailing_Zip { get; set; }

    public string Mailing_Zip_Plus_4 { get; set; }

    public string Mailing_Country { get; set; }

    public string Mailing_Postal_Code { get; set; }

    public string Career_Center { get; set; }

    public string City { get; set; }

    public string City_School_District { get; set; }

    public string County_Court__District { get; set; }

    public string Congressional_District { get; set; }

    public string Court_of_Appeals { get; set; }

    public string Education_Service_Center { get; set; }

    public string Exempted_Village_School_District { get; set; }

    public string Library_District { get; set; }

    public string Local_School_District { get; set; }

    public string Municipal_Court_District { get; set; }

    public string Precinct { get; set; }

    public string Precinct_Code_ { get; set; }

    public string State_Board_of_Education { get; set; }

    public string State_Representative_District_ { get; set; }

    public string State_Senate_District { get; set; }

    public string Township { get; set; }

    public string Village { get; set; }

    public string Ward { get; set; }
}