// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreprocessingData.Models;

public partial class OhioPartyLookup
{
    public long MainPartyId { get; set; }

    public string PartyName { get; set; }

    public string OhioLookupCode { get; set; }
}