// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreprocessingData.Models;

public partial class OhioElections
{
    public long ElectionID { get; set; }

    public string ElectionName { get; set; }

    public DateOnly? ElectionDate { get; set; }

    public string ElectionType { get; set; }
}