// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreprocessingData.Models;

public partial class OhioVoterElectionRecord
{
    public long ElectionRecordId { get; set; }

    public string SOS_Voter_Id { get; set; }

    public string ElectionName { get; set; }

    public string VoterRegisteredAs { get; set; }
}